### ISSUE TITLE
请问只安装Jenkins和Gerrit，怎么修改docker-compose.yml文件？

### ISSUE THREAD

**Issue by zengqingfu1442** [baosong818/Gerrit-Gitlab-Jenkins-SonarQube#1]
请问只安装Jenkins和Gerrit，怎么修改docker-compose.yml文件？ @baosong818

**Comment by baosong818** [comment]
稍等，我琢磨琢磨

**Comment by baosong818** [comment]
docker-compose.yaml配置文件留下面四个，并删除一切没用的sonarquebe、gitlab的depends_on和external_links
mysql_gerrit
gerrit
jenkins
nginx

初始化init_devops_system_centos7.sh脚本，我认为没必要改，一切完成后记得删除sonar和gitlab的目录即可
nginx/nginx.conf删除gitlab和sonar就行了

**Comment by zengqingfu1442** [comment]
请问第6步中“需要将以下jenkins用户的id_rsa.pub内容粘贴到gitlab、gerrit的公钥框中”，这个gitlab,gerrit的公钥框是在哪里啊？

**Comment by baosong818** [comment]
http://gerrit.demo.com/#/settings/ssh-keys
gerrit右上角-setting-SSH Public Keys

**Comment by zengqingfu1442** [comment]
gitlab初始化的时候输入完新密码之后，登录用户名是什么啊？

**Comment by baosong818** [comment]
root

**Comment by zengqingfu1442** [comment]
1. 请问这个docker部署的gerrit和jenkins怎么与已经有的gitlab集成起来啊？
2. 浏览器打开http://sonarqube.demo.com/报“502 Bad Gateway”错误
3. 单机部署的gerrit和Jenkins master稳定好用吗？能支撑多少人规模的？

**Comment by baosong818** [comment]
1、gerrit、jenkins、gitlab互通，只要网络、端口通，其次就是通过密钥互联，拉取、同步代码
2、netstat -lnpt看看有没有9000端口，这个sonar启动的奇慢
3、得看你服务器配置了吧，其次看使用量，你动不动就要提交个代码预编译下，这玩意不好估算

我提交个pdf，你看看怎么互通的吧。最开始用编译、二进制的方法部署的，后期才起的docker

**Comment by baosong818** [comment]
提交了两个pdf，你自己看看

**Comment by zengqingfu1442** [comment]
sonarqube代码扫描工具有没有比较好的搭建和使用文档？这个项目中sonarqube总是起不来，docker logs看了一下是elasticsearch进程内存溢出：
“2019.07.15 03:15:50 WARN  web[][o.a.c.l.WebappClassLoaderBase] The web application [ROOT] appears to have started a thread named [elasticsearch[_client_][transport_worker][T#14]] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:”

**Comment by baosong818** [comment]
export SONAR_SCANNER_OPTS="-Xmx512m"
在sonar docker里把这个变量打进去试试，咱这虚拟机什么配置啊

**Comment by zengqingfu1442** [comment]
是写到dockerfile里，重新做一个sonarqube镜像？

**Comment by zengqingfu1442** [comment]
直接在docker-compose.yml里面设置这个环境变量行不？

**Comment by baosong818** [comment]
你先告诉我你这服务器配置，我测试了无数遍这个docker-compose.yaml，也没见起不来啊

**Comment by baosong818** [comment]
主要你这个提示，明显是内存够造成的。我测试的4GB的REM

**Comment by zengqingfu1442** [comment]
就是我自己的物理机，16GB内存，8CPU(s)

**Comment by baosong818** [comment]
怪了，哈哈哈
我还是虚拟机呢
你试试把sonar和sonar-mysql单独拿出来，看看起得来吗

**Comment by zengqingfu1442** [comment]
我看最新的sonarqube-7.9.1-cmmunity不使用MySQL做存储数据库了

**Comment by baosong818** [comment]
稍等，我看看啊。我重新部署下，好像我记得我写的时候是7.8

**Comment by baosong818** [comment]
你再试试，重新clone，我把sonar固定在7.8版本了，没问题。7.9就是内存异常
我有时间看看7.9
